---
version: '3'
services:
  postgresql: # Application relational database
    image: postgres:11.1
    restart: unless-stopped
    ports:
      - '35432:5432'
    environment:
      POSTGRES_PASSWORD: &postgresql_password topsecret!
      POSTGRES_USER: &postgresql_user dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:5.0-alpine3.8
    restart: unless-stopped
    ports:
      - '36379:6379'
  application:
    image: ${APP_DOCKER_IMAGE}
    restart: on-failure:2
    environment:
      TIMEZONE: ${TIMEZONE}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
      POSTGRES_HOST: postgresql
      POSTGRES_USER: *postgresql_user
      POSTGRES_PASSWORD: *postgresql_password
    links:
      - "postgresql:postgres-01"
      - "redis:redis-01"
  dramatiq:
    image: ${APP_DOCKER_IMAGE}
    restart: on-failure:2
    entrypoint: dramatiq app.tasks
    environment:
      TIMEZONE: ${TIMEZONE}
      POSTGRES_HOST: postgresql
      POSTGRES_USER: *postgresql_user
      POSTGRES_PASSWORD: *postgresql_password
    links:
      - "postgresql:postgres-01"
      - "redis:redis-01"

volumes:
  postgres_data:
