---
version: 2

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - pontomaisoumenos-v1-{{ .Branch }}-{{ checksum "Dockerfile" }}
          paths:
            - /caches/pontomaisoumenos.tar

      - run:
          name: Prepare | Install make
          command: |
            apk add make

      - run:
          name: Docker | Load the cached image layers
          command: |
            make CACHE_DIR=/caches load-docker-image

      - run:
          name: Docker | Build application container image
          command: |
            make docker-build

      - run:
          name: Docker | Save image layers to cache
          command: |
            mkdir -p /caches
            make CACHE_DIR=/caches save-docker-image

      - save_cache:
          key: pontomaisoumenos-v1-{{ .Branch }}-{{ checksum "Dockerfile" }}
          paths:
            - /caches/pontomaisoumenos.tar
  test:
    docker:
      - image: python:3.7-slim-buster
    steps:
      - run:
          name: Prepare | Install Git
          command: |
            apt-get update
            apt-get install -y git
      - checkout
      - run:
          name: Test | Install dependencies
          command: |
            apt-get install -y python3-dev gcc \
              libffi-dev make
            python3 -m pip install flake8 pytest
            python3 -m pip install -r requirements.txt

      - run:
          name: Test | Running PyTest
          command: |
            make tests

workflows:
  version: 2
  build:
    jobs:
      - test
    # - build # Not used ATM
